name: test-binaries
on:
  workflow_dispatch:

env:
  DOCKER_IMAGE: quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/client-server
  DOCKER_IMAGE_VERSION: on-pr-d6800cce4b23319b33fd86e577285319c2e709ae

jobs:
  get-binaries:
    name: Get client binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache clients
        id: cache-clients
        uses: actions/cache@v3
        with:
          path: ./target/clients
          key: clients-${{ env.DOCKER_IMAGE_VERSION }}
      - name: Get image with CLI runtimes
        if: steps.cache-clients.outputs.cache-hit != 'true'
        shell: bash
        run: |
          mkdir target
          docker cp $(docker create --name client-server-con $DOCKER_IMAGE:$DOCKER_IMAGE_VERSION):/var/www/html/clients target && docker rm client-server-con

  test-runtimes:
    name: Test client binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Cache clients
        id: cache-clients
        uses: actions/cache@v3
        with:
          path: ./target/clients
          key: clients-${{ env.DOCKER_IMAGE_VERSION }}
      - name: List binaries
        if: steps.cache-clients.outputs.cache-hit != 'true'
        shell: bash
        run: |
          ls -la ./target/clients
          find ./target/clients
