name: test-binaries
on:
  workflow_dispatch:

jobs:
  test-binary:
    name: Test binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      
      - name: Echo HI
        shell: bash
        run: |
          echo "HI"
          docker -v          
