name: test-binaries
on:
  workflow_dispatch:

env:
  DOCKER_IMAGE: quay.io/redhat-user-workloads/rhtas-tenant/rhtas-stack-1-0-beta/client-server
  DOCKER_IMAGE_VERSION: on-pr-d6800cce4b23319b33fd86e577285319c2e709ae

jobs:
  get-files:
    name: Get runtime files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4   
      - name: Get image with CLI runtimes
        shell: bash
        run: |
          mkdir target
          docker cp $(docker create --name client-server-con $DOCKER_IMAGE:$DOCKER_IMAGE_VERSION):/var/www/html/clients target && docker rm client-server-con
          find target
