name: test-binaries
on:
  workflow_dispatch:

jobs:
  get-files:
    name: Get runtime files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4   
      - name: Get image with CLI runtimes
        shell: bash
        run: |
          docker -v          
